### ISSUE TITLE
Alternate audio streams not playing

### ISSUE THREAD

**Issue by scan** [mangui/flashls#91] opened 2014-10-07 16:58 UTC
I don't know if it's even supported, but I have a playlist like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",CODECS="mp4a.40.5",LANGUAGE="en",NAME="Stereo",DEFAULT=TRUE,URI="stereo/playlist.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",CODECS="mp4a.40.5",LANGUAGE="en",NAME="Surround",DEFAULT=FALSE,URI="surround/playlist.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=911000,RESOLUTION=1024x436,CODECS="avc1.4d001f,mp4a.40.5",AUDIO="aac"
sintel-1024/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1810000,RESOLUTION=1280x544,CODECS="avc1.4d001f,mp4a.40.5",AUDIO="aac"
sintel-1280/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2546000,RESOLUTION=2048x872,CODECS="avc1.4d001f,mp4a.40.5",AUDIO="aac"
sintel-2048/playlist.m3u8
```

This format does what I want it to in the default iOS player.

I'm using the grind player and it works fine, but there is no sound. There is a little Audio switching symbol that allows me to choose "Default" (even though default is labelled Stereo) and "Surround". No matter what I choose, neither these nor the sound in the video files are played. Once I remove the `,AUDIO="aac"` part from the video streams, the audio plays fine - but there is no alternative audio playing.

What I need is some way (any way, really) to be able to add alternative Audio (AAC) to the video, choosable in the Grind player. Is that possible?

**Comment by mangui** [comment] 2015-01-28 09:58
duplicate of #6

**Closed by mangui** 2015-01-28 09:58 UTC
Labels: duplicate, enhancement
