### ISSUE TITLE
video does not displayed on chrome and IE.

### ISSUE THREAD

**Issue by shivamg705** [mangui/flashls#185] opened 2015-01-19 07:51 UTC
Hi mangui,

I am using your plugin to play hls streaming.It work fine with Mozilla and safari.but in chrome and IE video is playing with only sound.(i.e video picture is not displayed).I am mentioning following code which used to hls streaming.

<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
			   xmlns:s="library://ns.adobe.com/flex/spark" 
			   xmlns:mx="library://ns.adobe.com/flex/mx" minWidth="955" minHeight="600"
			   applicationComplete="initPlayer(event)" xmlns:ui="ui.*">
	<fx:Declarations>
		
	</fx:Declarations>
	
	<fx:Script>
		<![CDATA[
			import mx.controls.Alert;
			import mx.core.FlexGlobals;
			import mx.events.FlexEvent;
			
			import org.mangui.hls.HLSSettings;
			import org.mangui.osmf.plugins.HLSPlugin;
			import org.osmf.elements.VideoElement;
			import org.osmf.events.MediaFactoryEvent;
			import org.osmf.events.MediaPlayerCapabilityChangeEvent;
			import org.osmf.media.MediaElement;
			import org.osmf.media.MediaFactory;
			import org.osmf.media.MediaPlayer;
			import org.osmf.media.MediaPlayerSprite;
			import org.osmf.media.PluginInfoResource;
			import org.osmf.media.URLResource;
			import org.osmf.net.StreamingURLResource;
			import org.osmf.utils.URL;
			
			public var mediaPlayerSprite:MediaPlayerSprite;
			public var mediaPlayer:MediaPlayer;
			public var mediaFactory:MediaFactory;
			public var mediaElement:MediaElement;
			
			public function initPlayer(event:FlexEvent):void
			{
				
				mediaPlayerSprite = new MediaPlayerSprite();
				mediaPlayer = mediaPlayerSprite.mediaPlayer;
				mediaFactory = mediaPlayerSprite.mediaFactory;
				
				mediaPlayer.autoPlay = true;
				mediaPlayer.autoRewind = false;
				
				mediaPlayerSprite.width = stage.stageWidth;
				mediaPlayerSprite.height = stage.stageHeight;
				
				mediaContainerUIComponent.addChild(mediaPlayerSprite);
				
				mediaPlayer.addEventListener(MediaPlayerCapabilityChangeEvent.IS_DYNAMIC_STREAM_CHANGE, onIsDynamicStreamChange);
				
				loadPlugin();
				
			}
			private function onIsDynamicStreamChange(event:MediaPlayerCapabilityChangeEvent):void {
				if (event.enabled) {
					var streamIndex:int = mediaPlayer.currentDynamicStreamIndex;
					mediaPlayer.autoDynamicStreamSwitch = true;
					
				}
			}
			private function loadPlugin():void
			{
				var PluginLoad:HLSPlugin;
				
				HLSSettings.logInfo = true;
				
				var pluginInfoClass:Class = getDefinitionByName( "org.mangui.osmf.plugins.HLSPlugin" ) as Class;
				var pluginResources:PluginInfoResource = new PluginInfoResource(new pluginInfoClass());
				
				mediaFactory.addEventListener(MediaFactoryEvent.PLUGIN_LOAD,function():void{
					launchMedia();
				});
				
				mediaFactory.addEventListener(MediaFactoryEvent.PLUGIN_LOAD_ERROR,function(event:MediaFactoryEvent):void{
					Alert.show("error");
				});
				
				mediaFactory.loadPlugin(pluginResources);
				
			}
			private function launchMedia():void {
				//Alert.show("Success");
				mediaElement = mediaFactory.createMediaElement(new StreamingURLResource("http://127.0.0.1:1935/vod/smil:mysmil.smil/playlist.m3u8"));
				mediaPlayerSprite.media = mediaElement;
			}
		]]>
	</fx:Script>
	
	<mx:Canvas id="mediaContainerHolder">
		<ui:MediaContainerUIComponent id="mediaContainerUIComponent" width="100%" height="100%"/>				
	</mx:Canvas>
	
	<mx:Text id="debug" fontSize="16" fontWeight="bold" color="0xDFDFDF" x="0" y="0" text="" />
	
</s:Application>

I hope you will help me,Thanks in advance

**Comment by kalimba** [comment] 2015-01-19 09:48
You will need to check if the mediaplayersprite object correctly added to stage. You should try to set width and height parameters of it. The mediaPlayer plays video file with audio without add the mediaplayer display object to stage.

**Comment by shivamg705** [comment] 2015-01-19 10:41
Thanks for reply.

i have set the default value such like
 mediaPlayerSprite.width = 450;
 mediaPlayerSprite.height = 400; then i find that it still does not works chrome and IE.

Thanks

**Comment by kalimba** [comment] 2015-01-19 11:25
I did some test width following codes. It works Chrome, IE, Firefox.

Compiled files are at http://test.webdeveloperzone.net/osmf/videotest_bin-release.rar

as3

```
package
{
	import flash.display.Sprite;
	import flash.utils.getDefinitionByName;
	
	import org.mangui.HLS.HLSSettings;
	import org.mangui.osmf.plugins.HLSPlugin;
	import org.osmf.events.MediaFactoryEvent;
	import org.osmf.events.MediaPlayerCapabilityChangeEvent;
	import org.osmf.media.MediaElement;
	import org.osmf.media.MediaFactory;
	import org.osmf.media.MediaPlayer;
	import org.osmf.media.MediaPlayerSprite;
	import org.osmf.media.PluginInfoResource;
	import org.osmf.net.StreamingURLResource;
	
	
	public class VideoTest2 extends Sprite
	{
		private var mediaPlayerSprite:MediaPlayerSprite;
		private var mediaFactory:MediaFactory;
		private var mediaPlayer:MediaPlayer;
		private var mediaElement:MediaElement;
	
		public function VideoTest2()
		{
			initPlayer();
		}
		
		public function initPlayer():void
		{
			
			mediaPlayerSprite = new MediaPlayerSprite();
			mediaPlayer = mediaPlayerSprite.mediaPlayer;
			mediaFactory = mediaPlayerSprite.mediaFactory;
			
			mediaPlayer.autoPlay = true;
			mediaPlayer.autoRewind = false;
			
			mediaPlayerSprite.width = stage.stageWidth;
			mediaPlayerSprite.height = stage.stageHeight;
			
			addChild(mediaPlayerSprite);
			
			mediaPlayer.addEventListener(MediaPlayerCapabilityChangeEvent.IS_DYNAMIC_STREAM_CHANGE, onIsDynamicStreamChange);
			
			loadPlugin();
			
		}
		private function onIsDynamicStreamChange(event:MediaPlayerCapabilityChangeEvent):void {
			if (event.enabled) {
				var streamIndex:int = mediaPlayer.currentDynamicStreamIndex;
				mediaPlayer.autoDynamicStreamSwitch = true;
				
			}
		}
		private function loadPlugin():void
		{
			var PluginLoad:HLSPlugin;
			
			HLSSettings.logInfo = true;
			
			var pluginInfoClass:Class = getDefinitionByName( "org.mangui.osmf.plugins.HLSPlugin" ) as Class;
			var pluginResources:PluginInfoResource = new PluginInfoResource(new pluginInfoClass());
			
			mediaFactory.addEventListener(MediaFactoryEvent.PLUGIN_LOAD,function():void{
				launchMedia();
			});
			
			mediaFactory.addEventListener(MediaFactoryEvent.PLUGIN_LOAD_ERROR,function(event:MediaFactoryEvent):void{
				trace("error");
			});
			
			mediaFactory.loadPlugin(pluginResources);
			
		}
		private function launchMedia():void {
			mediaElement = mediaFactory.createMediaElement(new StreamingURLResource("http://uygulama.localhost/source/demo/assets/video/sl_vod.m3u8"));
			mediaPlayerSprite.media = mediaElement;
		}
	}
}
```

HTML
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
	<script src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
</head>

<body>

<div id="container_player" style="width:640px;height:360px">
	<div id="player"></div>
</div>


<script>
	swfobject.embedSWF(
		'VideoTest2.swf',
		"player",
		"100%",
		"100%",
		"11.0.0",
		null,
		{}, //flash vars
		{},//params
		{},/*atributes*/
		function checkFlash(e)
		{
			if (e.success)
			{
				console.log("Flash loaded successfully");
			} else {
				document.getElementById("player").innerHTML = "<p>Flash error.</p>"
			}
		}
	);
</script>
			
</body>
</html>
```

**Comment by shivamg705** [comment] 2015-01-19 12:30
Thanks for reply

Actually i have created my app as flex project(web project) because i have made all playback controls in mxml file like play pause and scrub bar etc.so i have tried to play hls streaming using your plugin.if you have any idea then please with me. I really needed this.

I appreciate your help.
Thanks

**Comment by kalimba** [comment] 2015-01-19 13:50
Please try to add "OSMFSettings.enableStageVideo = false;"  at the begining of initPlayer method. It will work fine.

**Comment by shivamg705** [comment] 2015-01-20 09:55
Thank you very much,it work fine for me.

**Comment by mangui** [comment] 2015-01-22 21:04
closing as the issue is resolved

**Closed by mangui** 2015-01-22 21:04 UTC
Labels: question
