### ISSUE TITLE
error: hls.stage not set, cannot parse TS data !!!

### ISSUE THREAD

**Issue by dtniland** [mangui/flashls#242] opened 2015-04-08 20:55 UTC
We are seeing this in the details property of MediaErrorEvent.MEDIA_ERROR quite often now in 0.4.0.5.  It does not seem to reproduce in 0.4.0.4.

We are using the reference file: http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

It seems to get kicked out when the code tries the parse the hls manifest.

**Comment by mangui** [comment] 2015-04-08 21:05
duplicate of #232

**Closed by mangui** 2015-04-08 21:05 UTC
