### ISSUE TITLE
Does plugin support clipStartTime and clipEndTime?

### ISSUE THREAD

**Issue by lerivin** [mangui/flashls#188] opened 2015-01-23 20:58 UTC
On StreamingURLResource does the plugin support defining a clip start and end time. My testing so far is not working.

**Comment by kalimba** [comment] 2015-01-24 09:36
It would be nice, but flashhls dosn't support subclipping feature of OSMF. There is an issue at [here](https://github.com/mangui/flashls/issues/9) .

**Comment by mangui** [comment] 2015-01-24 12:33
closing as duplicate of https://github.com/mangui/flashls/issues/9

**Closed by mangui** 2015-01-24 12:33 UTC
