### ISSUE TITLE
Player stalls when switching qualities

### ISSUE THREAD

**Issue by cmelendez** [mangui/flashls#172] opened 2015-01-05 20:26 UTC
Hi @mangui,

First, happy new year! Second, I believe we have found a bug (and a possible solution).

**The case/steps/info:**

1. Player: StrobeMediaPlayback with flashls' latest build.
2. Player loads m3u8. Playlist has 4 variants ranging from ~350Kbps to ~1800Kbps and current bandwidth is close to 100Mbps.
3. Player starts playback at highest level possible.
4. Bandwidth is then throttled to 750Kbps (or anything that requires the plugin to start using a lower level).
5. Player requests a lower level manifest.
6. Player goes to buffering state (no playback here, of course)
7. Player requests segments from that lower manifest and segment gets cancelled a few bytes later.
8. Player keeps requesting and canceling that same segment over and over and player never goes out of buffering state (iOS didn't have this problem).

**The logs:**

Player is playing video

```
 DEBUG:6 tags extracted
VM2883:1 DEBUG:Loaded position/duration/sliding/discontinuity:49.67/0.00/10.03/false
VM2884:1 DEBUG:AutoBufferManager:minBufferLength:60
VM2887:1 DEBUG:loading completed
VM2888:1 DEBUG:Loading       duration/RTT/length/speed:65766/415/2085108/248 kb/s
5VM2889:1 DEBUG:AVC: AUD, SEI, NDR slices
VM2894:1 DEBUG:5 tags extracted
VM2895:1 DEBUG:Loaded position/duration/sliding/discontinuity:49.87/0.00/9.83/false
VM2896:1 DEBUG:AutoBufferManager:minBufferLength:60
VM2897:1 DEBUG:TS: flushing demux
VM2898:1 DEBUG:TS: complete Audio PES found at end of segment, parse it
VM2899:1 DEBUG:TS: partial AVC PES at end of segment
VM2900:1 DEBUG:TS: flush 15 tags
VM2901:1 DEBUG:15 tags extracted
VM2902:1 DEBUG:Loaded position/duration/sliding/discontinuity:49.69/0.35/10.01/false
VM2903:1 DEBUG:AutoBufferManager:minBufferLength:60
VM2904:1 DEBUG:TS: parsing complete
VM2905:1 DEBUG:m/M audio PTS:18912575/18922560
VM2906:1 DEBUG:m/M video PTS:18912489/18922532
VM2907:1 DEBUG:Delta audio/video m/M PTS:-86/-28
VM2908:1 DEBUG:Total Process duration/length/bw:65824/2085108/247 kb/s
VM2909:1 DEBUG:Loaded        11425 of [11427,11431],level 4 m/M PTS:18912575/18922560
VM2910:1 ERROR:updateFragment:seqnum 11425 not found!
VM2911:1 DEBUG:AutoBufferManager:minBufferLength:60
```

Player requests lower level then "[new_seqnum](https://github.com/mangui/flashls/blob/altaudio/src/org/mangui/hls/loader/FragmentLoader.as#L648)" becomes NaN and player stalls 
```
 DEBUG:Loaded        11425 of [11427,11431],level 4 m/M PTS:18912575/18922560
VM2910:1 ERROR:updateFragment:seqnum 11425 not found!
VM2911:1 DEBUG:AutoBufferManager:minBufferLength:60
VM2913:1 DEBUG:sftm < 1-_switchdown[current_level]=0.5747126436781609
2VM2914:1 DEBUG:switch to level 0
VM2916:1 DEBUG:(re)load Playlist
VM2917:1 DEBUG:HLSDynamicStreamTrait:_qualitySwitchHandler:0
VM2918:1 DEBUG:HLSDynamicStreamTrait:switchingChangeStart(newSwitching/index):false/0
VM2919:1 DEBUG:HLSDynamicStreamTrait:getBitrateForIndex(0)=345.4
4VM2920:1 DEBUG:loadnextfragment : playlist not received for level:0
VM2926:1 DEBUG:level 0 playlist:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:11427
#EXTINF:10.010,
http://foo-bar-com/playlist_b250_11427.ts
#EXTINF:10.010,
http://foo-bar-com/playlist_b250_11428.ts
#EXTINF:10.010,
http://foo-bar-com/playlist_b250_11429.ts
#EXTINF:10.010,
http://foo-bar-com/playlist_b250_11430.ts
#EXTINF:10.010,
http://foo-bar-com/playlist_b250_11431.ts

VM2927:1 DEBUG:updateFragments: unknown PTS info for this level
VM2928:1 DEBUG:Level 0 Live Playlist parsing finished: reload in 9623 ms
DEBUG:loadnextfragment()
VM2930:1 DEBUG:loadnextfragment : getSeqNumNearestPTS(level,pts,cc:0,18912575,0)=-1
VM2931:1 DEBUG:loadnextfragment : getFirstSeqNumfromContinuity(level,cc:0,0)=11427
VM2932:1 DEBUG:analyzing PTS 11427 of [11427,11431],level 0
VM2933:1 DEBUG:loading fragment:http://foo-bar-com/playlist_b250_11427.ts
VM2934:1 DEBUG:probe fragment type
VM2935:1 DEBUG:MPEG2-TS found
VM2936:1 DEBUG:TS: PAT found.PMT PID:480
VM2937:1 DEBUG:TS: PMT found
VM2938:1 DEBUG:TS: Selected video PID: 481
VM2939:1 DEBUG:TS: Found 1 audio tracks
VM2940:1 DEBUG:TS: selected AAC PID: 482
VM2941:1 DEBUG:AVC: AUD, SPS, PPS, SEI, SEI, IDR slices
VM2942:1 DEBUG:AVC: width/height:256/144
VM2943:1 DEBUG:AVC: H264 Baseline level 12
VM2944:1 DEBUG:AVC: AUD, SEI, NDR slices
VM2945:1 DEBUG:AAC: LC, 48000 Hz 2 channel(s)
VM2946:1 DEBUG:TS/AAC: insert ADIF TAG
18VM2947:1 DEBUG:AVC: AUD, SEI, NDR slices
VM2965:1 DEBUG:53 tags extracted
VM2966:1 DEBUG:analyzed  PTS 11427 of [11427,11431],level 0 m PTS:18932588
VM2967:1 DEBUG:analyzed PTS : getSeqNumNearestPTS(level,pts,cc:0,18912575,0)=11428
VM2968:1 DEBUG:PTS analysis done on 11427, matching seqnum is 11428 of [11427,11431],cancel loading and get new one
VM2969:1 DEBUG:TS: cancel demux
VM2970:1 DEBUG:loadnextfragment()
VM2971:1 DEBUG:loadnextfragment : getSeqNumNearestPTS(level,pts,cc:0,18912575,0)=11427
VM2972:1 DEBUG:NaN of [11427,11431],level 0
VM2973:1 DEBUG:loadnextfragment()
VM2974:1 DEBUG:loadnextfragment : getSeqNumNearestPTS(level,pts,cc:0,18912575,0)=11427
VM2975:1 DEBUG:NaN of [11427,11431],level 0
VM2976:1 DEBUG:loadnextfragment()
VM2977:1 DEBUG:loadnextfragment : getSeqNumNearestPTS(level,pts,cc:0,18912575,0)=11427
VM2978:1 DEBUG:NaN of [11427,11431],level 0
```

The hacky and quick way of fixing the issue is adding this below line [647](https://github.com/mangui/flashls/blob/altaudio/src/org/mangui/hls/loader/FragmentLoader.as#L647) in [FragmentLoader.as](https://github.com/mangui/flashls/blob/altaudio/src/org/mangui/hls/loader/FragmentLoader.as#L647)
```
            if (isNaN(new_seqnum)) {
              new_seqnum = _levels[level].start_seqnum + 1;
            }
```

I didn't wanted to make a PR since I'm sure this fix is far from decent but at least it seems to fix the problem ~~completely~~ partially.

As always, thnxs for your time.

c.

**Comment by cmelendez** [comment] 2015-01-05 21:58
Extra FYI: The hack works for live streams, VODs don't recover as expected.

**Comment by mangui** [comment] 2015-01-05 23:00
Thanks for the detailed report, indeed this is not the best solution, i will try to find a better one soon.

**Comment by mangui** [comment] 2015-01-08 22:32
Hi @cmelendez I didn't repro but I think I found the root cause, from code analysis.
would you mind retesting with latest flashls/altaudio ?

**Comment by cmelendez** [comment] 2015-01-08 23:57
That did the trick. Adaptive bitrate is working again.
Any ideas what might be missing in the encoding that triggered the error?

Thank you!

**Comment by mangui** [comment] 2015-01-10 10:35
It was not an encoding issue, there was a real issue in flashls.

**Comment by mangui** [comment] 2015-01-22 22:23
closing, as issue is fixed

**Closed by mangui** 2015-01-22 22:23 UTC
Labels: bug
