### ISSUE TITLE
Is there a way to get the values from #EXT-X-PROGRAM-DATE-TIME in the original time zone?

### ISSUE THREAD

**Issue by oripessach** [mangui/flashls#201] opened 2015-02-09 19:50 UTC
Currently, the program time is delivered in UTC, and there's no way to get the original timezone of the date transmitted in #EXT-X-PROGRAM-DATE-TIME. For my application (which needs to show the program time to the user) that's not appropriate. Is there a way to do that?

**Comment by flavioribeiro** [comment] 2015-02-09 20:21
hi @oripessach, flashls is [not considering the timezone](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/playlist/Manifest.as#L236-L246) when parsing the program-date-time. I don't think it is something hard to do, you just need to be careful when sum the timezone before creating the `Date` object.

**Comment by oripessach** [comment] 2015-02-09 21:36
Yeah, I saw that code. I think it will fail (as in, return the wrong time)
when the server and the client are in different time zones.

**Comment by mangui** [comment] 2015-02-10 21:07
Offsetting absolute time to retrieve local time is the responsability of the player, it is out of this lib scope.

**Comment by oripessach** [comment] 2015-02-10 21:40
Sadly, there's no way that the player can do that, because it can either
use the UTC time as is, or show it in its OWN locale, but not in the
original time zone.

If you can think of a way to do that, why, I'd love to hear it.

**Comment by oripessach** [comment] 2015-02-10 21:52
In case your comment is in response to what I said about the date parsing
code getting the wrong time, I wanted to clarify: The code will set the
wrong UTC time when the time zone of the player is different from the time
zone transmitted in the manifest, and there's nothing the client can do to:
a) Detect that the time is wrong, or b) correct the time so it's in the
correct time zone.

So basically, the library is giving the client the wrong information.

**Comment by mangui** [comment] 2015-02-13 10:05
date parsing/conversion is handled [here](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/playlist/Manifest.as#L248),
I am using [Date() constructor](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Date.html#Date%28%29). there are two potential issues there : 

 - the timezone is not parsed. 
 - also i am not clear whether Date() constructor is using local time or UTC time.

you might check this.
IMHO this is the only place where there could be potential issues, as 
[Date().getTime()](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Date.html#getTime%28%29) then returns the number of milliseconds since midnight January 1, 1970, universal time, for a Date object.
and this value is then returned in FRAGMENT_PLAYING event.

**Comment by mangui** [comment] 2015-03-08 17:28
this function could be useful to correctly parse DATE including timezone:
https://code.google.com/p/as3corelib/source/browse/trunk/src/com/adobe/utils/DateUtil.as#531

**Comment by mangui** [comment] 2015-03-08 17:30
Date() is using UTC,  then offseted by timezone
https://code.google.com/p/as3corelib/source/browse/trunk/src/com/adobe/utils/DateUtil.as#579

**Comment by mangui** [comment] 2015-03-08 18:01
@oripessach , now timezone info is correctly parsed if set in the Manifest
plz recheck

**Comment by oripessach** [comment] 2015-03-08 19:32
Thanks - I'll check it tomorrow morning.

**Comment by mangui** [comment] 2015-03-17 09:02
@oripessach just curious have you been able to check ?

**Comment by mangui** [comment] 2015-03-27 22:19
@oripessach i will close the ticket next week unless there are any remaining issues

**Comment by oripessach** [comment] 2015-05-15 17:20
Honestly, I haven't been able to test this. I had to made my own modifications to the version of the code I'm working with, and these modifications work for me, and the very particular use cases I have to deal with. I haven't been able to update to the latest version of flashls in quite some time.

**Comment by mangui** [comment] 2015-05-19 10:08
closing, plz reopen if the issue is still popping up

**Closed by mangui** 2015-05-19 10:08 UTC
Labels: question

**Comment by oripessach** [comment] 2015-05-19 12:11
Thanks. I'll keep an eye on it.
