### ISSUE TITLE
Bottom pixel stretched

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#418] opened 2015-10-23 00:30 UTC
In the development branch, I am seeing the bottom pixel of some levels of some streams. Here is an example screen capture: https://www.dropbox.com/s/qygt7v0jzgk3qtz/stretch%20bottom%20pixel.mov?dl=0

The video stream is available here: https://d2nj0bxv1v66qe.cloudfront.net/star-wars-the-force-awakens/manifest.m3u8

This problem is not present in flashls version 0.4.3.4.

**Comment by mangui** [comment] 2015-10-23 11:33
i checked your stream with chromeless and GrindPlayer, seeked at exact same position, and check for all levels, I cannot reproduce this bottom pixel issue.
also I checked https://github.com/mangui/flashls/compare/v0.4.3.4...dev and I don't see which changes could introduce this...
it might be a resize issue on your player ?

**Comment by MixMasterMitch** [comment] 2015-11-18 19:42
Were there any changes in the last 26 days that could be related to this? I am no longer able to reproduce this issue!

**Comment by mangui** [comment] 2015-11-18 21:10
well, I was not able to repro the issue either at that time....  closing

**Closed as completed by mangui** 2015-11-18 21:10 UTC
Labels: question, fixed/answered
