### ISSUE TITLE
Video distorted after seeking

### ISSUE THREAD

**Issue by schellkenig** [mangui/flashls#264] opened 2015-04-29 13:10 UTC
Hi,

we recently launched a cloud based transcoding portal (www.bitcodin.com). We can generate MPEG-DASH & HLS content and currently we are in the process of checking compatibility with the major player vendors.

Unfortunately, our HLS content sometimes looks very distorted after seeking with your plugin like shown below. An example M3U8 would be [1] but you can also generate HLS and/or MPEG-DASH content with the portal by your own (you get 25$ for free after sign up but we can increase that amount if you need more for testing).

Would be really great if you can provide us some feedback, it could also be that we have an error on our end as we are still in beta ;).

[1] http://eu-storage.bitcodin.com/bitStorage/3_0b7886b852baac40e511a446ec24db0e/1198_e4c1ce3674af7beb87d6cec184a24450/1198.m3u8

![image](https://cloud.githubusercontent.com/assets/3272986/7391359/d845150e-ee80-11e4-9492-a57dd687f20d.png)

Thanks,
Christopher

**Comment by mangui** [comment] 2015-04-30 08:40
Hi @schellkenig I see some unexpected errors in the JS console while playing your stream with chromeless player.
 chromeless
"ERROR:negative duration computed for Fragment (seqnum: 68, start_time:525.8221428571424, duration:-0.43057142857136205), there should be some duration drift between playlist and fragment!"

it means that fragment duration reported in the playlist seems not consistent with fragment duration retrieved from parsing the TS fragments.
both needs to be consistent to avoid issues while seeking.
while looking at your playlist i can see that all fragments (audio/video) have exactly the same duration  ... 
#EXTINF:7.9285714285714
this is a rather precise value but maybe not accurate :-) worth checking
cheers,
Mangui

**Comment by schellkenig** [comment] 2015-04-30 08:54
Thanks @mangui for the detailed feedback. Actually we generate variable length segments and we simply write the average duration in the #EXTINF which is in that case 7.9285714285714, quite precise as mentioned ;). That works for MPEG-DASH but is there a way to do something similar with HLS?

Anyway, we will try to gather the exact individual segment durations and write them into the m3u8.

Thanks again for your feedback!
Chris

**Comment by mangui** [comment] 2015-04-30 09:12
@schellkenig the issue is that in your case, the sum of the drift is bigger than a fragment duration.
this makes it quite tricky to seek and find the initial segment.

**Comment by samek** [comment] 2015-04-30 09:19
Just write exact duration. 

It should be available to you when the segment is made.

**Comment by schellkenig** [comment] 2015-04-30 10:32
@samek its unfortunately not that easy as our transcoding process is highly distributed and parallel and therefore very fast, but we will try to add that feature soon.

**Comment by mangui** [comment] 2015-06-26 17:08
closing, as playlist was broken (invalid fragment duration)

**Closed by mangui** 2015-06-26 17:08 UTC
Labels: invalid
