### ISSUE TITLE
Audio disappearing when seeking within buffer

### ISSUE THREAD

**Issue by Jokki57** [mangui/flashls#378] opened 2015-09-01 09:03 UTC
Hello, when seeking within buffer on second or third time audio disappears. This bug reproduces in all players (in your examples) and all playlists. Audio restores when buffer flushes and new chunks begin downloading.

**Comment by mangui** [comment] 2015-09-01 10:12
indeed I can reproduce :-(
it looks like it is a regression introduced between v0.4.2.1 and v0.4.2.2.
could you confirm that v0.4.2.1 works fine on your side ?

**Comment by Jokki57** [comment] 2015-09-01 12:38
Yes, v0.4.2.1 works fine

**Comment by mangui** [comment] 2015-09-01 15:20
@Jokki57 you might recheck with latest flashls/dev, issue should be fixed

**Comment by mangui** [comment] 2015-09-15 20:24
closing as fixed

**Closed as completed by mangui** 2015-09-15 20:24 UTC
Labels: bug, fixed/answered
