### ISSUE TITLE
Exception while playing an HSL stream

### ISSUE THREAD

**Issue by LionArt** [mangui/flashls#220] opened 2015-03-11 10:02 UTC
I get this expection while playing an HLS stream.

ArgumentError: Invalid parameter passed to method
 at org.osmf.traits::LoadTrait/setBytesLoaded()
 at org.mangui.osmf.plugins.traits::HLSNetStreamLoadTrait/_mediaTimeHandler()
 at flash.events::EventDispatcher/dispatchEventFunction()
 at flash.events::EventDispatcher/dispatchEvent()
 at org.mangui.hls::HLS/dispatchEvent()
 at org.mangui.hls.stream::StreamBuffer/_checkBuffer()
 at flash.utils::Timer/_timerDispatch()
 at flash.utils::Timer/tick()

**Comment by mangui** [comment] 2015-03-11 10:08
interesting, do you have a stream to reproduce ?

**Comment by mangui** [comment] 2015-03-11 10:24
FYI it fails here:
https://github.com/willwh/osmf/blob/fac113c5fb7d6724992247be39106e1caa00fcfa/framework/OSMF/org/osmf/traits/LoadTrait.as#L282-L285

this is called here:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/traits/HLSNetStreamLoadTrait.as#L61-L64

**Comment by mangui** [comment] 2015-03-11 22:07
could you provide either a stream or a debug log ?
is it a live stream ? this could explain some potential negative value in case playhead is behind live playlist.

**Comment by LionArt** [comment] 2015-03-11 22:14
Yes of course, I am still waiting for the customer to be back. Once I have those details I will udpate this issue.

**Comment by tarkanlar** [comment] 2015-03-12 10:21
Hi mangui thanks alot,

this is the url http://awsome.tr.tv/  
and this is the settings http://awsome.tr.tv/data/player.json 

maybe because of these values are negative?

"hls_fragmentloadmaxretry": -1,
"hls_manifestloadmaxretry": -1,

**Comment by mangui** [comment] 2015-03-12 23:05
Hi @tarkanlar plz recheck with flashls/dev, and tell me if you still reproduce your issue.
I removed one possible weakness that could happen in rare scenarios : live playhead + buffer size is behind live sliding window. this could theoretically happen in case of bad bw condition.

**Comment by mangui** [comment] 2015-03-27 22:02
Hi @tarkanlar any update ?

**Comment by sstankov** [comment] 2015-06-09 17:34
Hi there,

I was having this error. Setting the line:
<pre>
var time_loaded : Number = Math.max(0, Math.round(10 * (event.mediatime.position + event.mediatime.buffer)) / 10);
</pre>

Solve it for me

**Comment by mangui** [comment] 2015-06-09 17:56
great, closing as this is matching with the commited changes

**Closed by mangui** 2015-06-09 17:56 UTC
Labels: bug

**Comment by sstankov** [comment] 2015-06-10 16:31
Hi there, actually testing it further I saw that this fix directly stops the stream. 
I tested it and best way to be is directly to not send it:

<pre>
        private function _mediaTimeHandler(event : HLSEvent) : void {
            var time_total : Number = Math.round(10 * event.mediatime.duration) / 10;
            var time_loaded : Number = Math.round(10 * (event.mediatime.position + event.mediatime.buffer)) / 10;

            if (_time_total != time_total) {
                if (time_total < _time_loaded || time_total < 0) {
                    time_total = NaN;
                }
                _time_total = time_total;
                setBytesTotal(time_total);
            }

            if (_time_loaded != time_loaded && time_loaded <= time_total) {
				//
				if (!(isNaN(time_loaded) || time_loaded > bytesTotal || time_loaded < 0)) {
					_time_loaded = time_loaded;
					setBytesLoaded(time_loaded);
				}
            }
        };
</pre>

**Comment by sstankov** [comment] 2015-06-10 16:31
I think you should update the logic with this one
